# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1021, 664)
        self.flying_bird = QtWidgets.QPushButton(Form)
        self.flying_bird.setGeometry(QtCore.QRect(20, 210, 131, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.flying_bird.setFont(font)
        self.flying_bird.setObjectName("flying_bird")
        self.shoulder_push = QtWidgets.QPushButton(Form)
        self.shoulder_push.setGeometry(QtCore.QRect(20, 130, 131, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.shoulder_push.setFont(font)
        self.shoulder_push.setObjectName("shoulder_push")
        self.squat = QtWidgets.QPushButton(Form)
        self.squat.setGeometry(QtCore.QRect(20, 370, 131, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.squat.setFont(font)
        self.squat.setObjectName("squat")
        self.bend = QtWidgets.QPushButton(Form)
        self.bend.setGeometry(QtCore.QRect(20, 290, 131, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.bend.setFont(font)
        self.bend.setObjectName("bend")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(110, 10, 331, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.video = QVideoWidget(Form)
        self.video.setGeometry(QtCore.QRect(550, 10, 441, 601))
        self.video.setObjectName("video")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(21, 628, 75, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.help = QtWidgets.QPushButton(Form)
        self.help.setGeometry(QtCore.QRect(940, 630, 75, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.help.setFont(font)
        self.help.setObjectName("help")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "训练评估系统"))
        self.flying_bird.setText(_translate("Form", "哑铃飞鸟"))
        self.shoulder_push.setText(_translate("Form", "哑铃推肩"))
        self.squat.setText(_translate("Form", "深蹲"))
        self.bend.setText(_translate("Form", "二头弯举"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600; color:#0055ff;\">请选择您要做的训练</span></p></body></html>"))
        self.back.setText(_translate("Form", "返回"))
        self.help.setText(_translate("Form", "帮助"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
